---
# Database Secrets
apiVersion: v1
kind: Secret
metadata:
  name: rental-ml-database-secret
  namespace: rental-ml
  labels:
    app.kubernetes.io/name: rental-ml-system
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: postgres-secret
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  postgres-password: cG9zdGdyZXNfcGFzc3dvcmQ=  # postgres_password
  postgres-user: cG9zdGdyZXM=  # postgres
---
# Redis Secrets
apiVersion: v1
kind: Secret
metadata:
  name: rental-ml-redis-secret
  namespace: rental-ml
  labels:
    app.kubernetes.io/name: rental-ml-system
    app.kubernetes.io/component: redis
    app.kubernetes.io/instance: redis-secret
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  redis-password: cmVkaXNfcGFzc3dvcmQ=  # redis_password
---
# Application Secrets
apiVersion: v1
kind: Secret
metadata:
  name: rental-ml-app-secret
  namespace: rental-ml
  labels:
    app.kubernetes.io/name: rental-ml-system
    app.kubernetes.io/component: app
    app.kubernetes.io/instance: app-secret
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  secret-key: c3VwZXJfc2VjcmV0X2tleV9jaGFuZ2VfbWU=  # super_secret_key_change_me
  jwt-secret-key: and0X3NlY3JldF9rZXlfY2hhbmdlX21l  # jwt_secret_key_change_me
  sentry-dsn: ""  # Empty for now, add actual Sentry DSN if needed
---
# SSL/TLS Certificates (example)
apiVersion: v1
kind: Secret
metadata:
  name: rental-ml-tls-secret
  namespace: rental-ml
  labels:
    app.kubernetes.io/name: rental-ml-system
    app.kubernetes.io/component: tls
    app.kubernetes.io/instance: tls-secret
type: kubernetes.io/tls
data:
  # Add your actual certificate and key here
  # tls.crt: <base64-encoded-certificate>
  # tls.key: <base64-encoded-private-key>
---
# Monitoring Secrets
apiVersion: v1
kind: Secret
metadata:
  name: rental-ml-monitoring-secret
  namespace: rental-ml
  labels:
    app.kubernetes.io/name: rental-ml-system
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/instance: monitoring-secret
type: Opaque
data:
  # Grafana admin password
  grafana-admin-password: YWRtaW5fcGFzc3dvcmQ=  # admin_password
  # Alertmanager webhook URLs or API keys
  slack-webhook-url: ""  # Add actual Slack webhook URL if needed
  pagerduty-api-key: ""  # Add actual PagerDuty API key if needed