---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
  namespace: rental-ml
  labels:
    app.kubernetes.io/name: rental-ml-system
    app.kubernetes.io/component: scheduler
    app.kubernetes.io/instance: scheduler
    app.kubernetes.io/version: "1.0.0"
spec:
  replicas: 1  # Scheduler should only have one replica
  strategy:
    type: Recreate  # Use Recreate to avoid conflicts
  selector:
    matchLabels:
      app.kubernetes.io/name: rental-ml-system
      app.kubernetes.io/component: scheduler
      app.kubernetes.io/instance: scheduler
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rental-ml-system
        app.kubernetes.io/component: scheduler
        app.kubernetes.io/instance: scheduler
        app.kubernetes.io/version: "1.0.0"
      annotations:
        checksum/config: "{{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      serviceAccountName: rental-ml-app
      containers:
      - name: scheduler
        image: rental-ml-system:latest
        imagePullPolicy: IfNotPresent
        command: ["celery"]
        args: ["-A", "src.infrastructure.tasks.celery_app", "beat", "--loglevel=info", "--scheduler", "django_celery_beat.schedulers:DatabaseScheduler"]
        env:
        # Database configuration
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: rental-ml-app-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: rental-ml-app-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: rental-ml-app-config
              key: DB_NAME
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: rental-ml-database-secret
              key: postgres-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rental-ml-database-secret
              key: postgres-password
        # Redis configuration
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: rental-ml-app-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: rental-ml-app-config
              key: REDIS_PORT
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rental-ml-redis-secret
              key: redis-password
        # Celery configuration
        - name: CELERY_BROKER_URL
          value: "redis://:$(REDIS_PASSWORD)@$(REDIS_HOST):$(REDIS_PORT)/1"
        - name: CELERY_RESULT_BACKEND
          value: "redis://:$(REDIS_PASSWORD)@$(REDIS_HOST):$(REDIS_PORT)/2"
        - name: CELERY_TIMEZONE
          valueFrom:
            configMapKeyRef:
              name: rental-ml-celery-config
              key: CELERY_TIMEZONE
        - name: CELERY_ENABLE_UTC
          valueFrom:
            configMapKeyRef:
              name: rental-ml-celery-config
              key: CELERY_ENABLE_UTC
        # Application configuration
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: rental-ml-app-config
              key: APP_ENV
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: rental-ml-app-config
              key: LOG_LEVEL
        # Security
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: rental-ml-app-secret
              key: secret-key
        volumeMounts:
        - name: app-logs
          mountPath: /app/logs
        - name: scheduler-data
          mountPath: /app/scheduler
        - name: tmp
          mountPath: /tmp
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - celery
            - -A
            - src.infrastructure.tasks.celery_app
            - inspect
            - ping
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
        readinessProbe:
          exec:
            command:
            - celery
            - -A
            - src.infrastructure.tasks.celery_app
            - inspect
            - ping
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
      volumes:
      - name: app-logs
        persistentVolumeClaim:
          claimName: app-logs-pvc
      - name: scheduler-data
        emptyDir: {}  # Scheduler data can be ephemeral
      - name: tmp
        emptyDir: {}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      # Init containers to wait for dependencies
      initContainers:
      - name: wait-for-postgres
        image: postgres:15-alpine
        command: ['sh', '-c', 'until pg_isready -h postgres-service -p 5432; do echo waiting for postgres; sleep 2; done;']
        env:
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: rental-ml-database-secret
              key: postgres-user
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      - name: wait-for-redis
        image: redis:7-alpine
        command: ['sh', '-c', 'until redis-cli -h redis-service -p 6379 ping; do echo waiting for redis; sleep 2; done;']
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "100m"