---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: rental-ml
  labels:
    app.kubernetes.io/name: rental-ml-system
    app.kubernetes.io/component: worker
    app.kubernetes.io/instance: worker
    app.kubernetes.io/version: "1.0.0"
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
  selector:
    matchLabels:
      app.kubernetes.io/name: rental-ml-system
      app.kubernetes.io/component: worker
      app.kubernetes.io/instance: worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rental-ml-system
        app.kubernetes.io/component: worker
        app.kubernetes.io/instance: worker
        app.kubernetes.io/version: "1.0.0"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9540"
        prometheus.io/path: "/metrics"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      serviceAccountName: rental-ml-worker
      containers:
      - name: worker
        image: rental-ml-system:latest  # Replace with your actual image
        imagePullPolicy: IfNotPresent
        command: ["celery"]
        args: ["-A", "src.infrastructure.tasks.celery_app", "worker", "--loglevel=info", "--concurrency=2"]
        env:
        # Database configuration
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: rental-ml-app-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: rental-ml-app-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: rental-ml-app-config
              key: DB_NAME
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: rental-ml-app-config
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rental-ml-database-secret
              key: postgres-password
        # Redis/Celery configuration
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: rental-ml-app-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: rental-ml-app-config
              key: REDIS_PORT
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rental-ml-redis-secret
              key: redis-password
        - name: CELERY_BROKER_URL
          valueFrom:
            secretKeyRef:
              name: rental-ml-celery-secret
              key: celery-broker-url
        - name: CELERY_RESULT_BACKEND
          valueFrom:
            secretKeyRef:
              name: rental-ml-celery-secret
              key: celery-result-backend
        # Application configuration
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: rental-ml-app-config
              key: APP_ENV
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: rental-ml-app-config
              key: LOG_LEVEL
        # ML configuration
        - name: ML_MODEL_PATH
          valueFrom:
            configMapKeyRef:
              name: rental-ml-app-config
              key: ML_MODEL_PATH
        - name: ML_BATCH_SIZE
          valueFrom:
            configMapKeyRef:
              name: rental-ml-app-config
              key: ML_BATCH_SIZE
        # Security
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: rental-ml-app-secret
              key: secret-key
        volumeMounts:
        - name: app-logs
          mountPath: /app/logs
        - name: ml-models
          mountPath: /app/models
        - name: app-data
          mountPath: /app/data
        - name: tmp
          mountPath: /tmp
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        # Health checks for Celery workers
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "celery -A src.infrastructure.tasks.celery_app inspect ping -d celery@$(hostname)"
          initialDelaySeconds: 60
          periodSeconds: 60
          timeoutSeconds: 30
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "celery -A src.infrastructure.tasks.celery_app inspect active -d celery@$(hostname)"
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
      # Celery Exporter for Prometheus metrics
      - name: celery-exporter
        image: danihodovic/celery-exporter:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9540
          name: metrics
          protocol: TCP
        env:
        - name: CELERY_BROKER_URL
          valueFrom:
            secretKeyRef:
              name: rental-ml-celery-secret
              key: celery-broker-url
        - name: CELERY_RESULT_BACKEND
          valueFrom:
            secretKeyRef:
              name: rental-ml-celery-secret
              key: celery-result-backend
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      volumes:
      - name: app-logs
        persistentVolumeClaim:
          claimName: app-logs-pvc
      - name: ml-models
        persistentVolumeClaim:
          claimName: ml-models-pvc
      - name: app-data
        persistentVolumeClaim:
          claimName: app-data-pvc
      - name: tmp
        emptyDir: {}
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      # Init containers to wait for dependencies
      initContainers:
      - name: wait-for-postgres
        image: postgres:15-alpine
        command: ['sh', '-c', 'until pg_isready -h postgres-service -p 5432; do echo waiting for postgres; sleep 2; done;']
        env:
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: rental-ml-database-secret
              key: postgres-user
      - name: wait-for-redis
        image: redis:7-alpine
        command: ['sh', '-c', 'until redis-cli -h redis-service -p 6379 ping; do echo waiting for redis; sleep 2; done;']